name: NestJS CI/CD
on:
  push:
    branches: [main] # Trigger on pushes to the main branch
  # pull_request:
  #     branches: [main] # Trigger on pull requests to the main branch
jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: oven-sh/setup-bun@v2
      - name: Install app dependencies  and build
        run: bun i
      - name: Build app
        run: bun run build
      - name: Deploy app temp folder to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/electronic-invoice/browser/*"
          target: ${{ secrets.TARGET_PATH }}
          strip_components: 1
